# Generated by Django 5.1.5 on 2025-02-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webinars/images/'),
        ),
    ]
