# Generated by Django 5.1.5 on 2025-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_webinar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
