# Generated by Django 5.1.5 on 2025-02-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_booking_payment_confirmed_booking_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
