# Generated by Django 5.1.5 on 2025-02-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_meeting_link_webinar_meeting_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='meeting_url',
            new_name='webinar_url',
        ),
    ]
