# Generated by Django 5.1.5 on 2025-02-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_meeting_url_webinar_webinar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_active',
            field=models.BooleanField(default=True),
        ),
    ]
