# Generated by Django 5.1.5 on 2025-02-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_booking_booking_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_active',
            new_name='is_active',
        ),
    ]
