# Generated by Django 5.1.5 on 2025-02-17 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_video_duration_video_thumbnail_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='previews/'),
            preserve_default=False,
        ),
    ]
